repositories {
    mavenCentral()
    // the 5.2 snapshot of Micronaut Core, for the bean definition writer fix that has the @PreDestroy callback of
    // an intercepted bean invoked; remove once 5.2 is released
    maven {
        url = 'https://central.sonatype.com/repository/maven-snapshots/'
        mavenContent {
            snapshotsOnly()
        }
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
