projectVersion=1.0.0-SNAPSHOT
projectGroup=io.micronaut.interceptor

title=Micronaut Jakarta Interceptors
projectDesc=A Jakarta Interceptors implementation built on Micronaut compile-time AOP
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-jakarta-interceptors
developers=Denis Stepanov

org.gradle.caching=true
org.gradle.jvmargs=-Xmx1g
predictiveTestSelection=false

coreDocsUrl=https://docs.micronaut.io/latest/api/io/micronaut/
guideUrl=https://docs.micronaut.io/latest/guide/
